// ═══════════════════════════════════════════════════════════════
// MEDAZON HEALTH — PANEL REGISTRY
// Static configuration for all workspace panels
// Defines IDs, labels, icons, default sizes, colors, lock behavior
// ═══════════════════════════════════════════════════════════════

import {
  Pill, ClipboardList, FileText, CalendarDays, AlertTriangle,
  Activity, User, AlertCircle, FlaskConical, Syringe, FolderOpen,
  Users, Wine, Scissors, Building2, ClipboardCheck, DollarSign,
  MessageSquare, ArrowRight, Shield, Stethoscope, Video,
  Heart, PenTool, CheckSquare, BookOpen,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PANEL_ID } from '@/lib/constants'
import type { PanelId } from '@/lib/constants'

// ─── PANEL CONFIG TYPE ───────────────────────────────────────
export interface PanelConfig {
  id: PanelId
  label: string
  icon: LucideIcon
  color: string           // Hex color for toolbar button + active indicator
  hoverBg: string         // Tailwind hover class for toolbar button
  defaultSize: { width: number; height: number }
  minSize: { width: number; height: number }
  defaultPosition: { x: number; y: number }
  defaultLocked: boolean  // If true, starts in locked grid position
  defaultOpen: boolean    // If true, opens when workspace loads
  locksWithChart: boolean // If true, read-only when chart is Signed/Closed
  category: 'clinical' | 'administrative' | 'communication' | 'system'
}

// ─── PANEL REGISTRY ──────────────────────────────────────────
export const PANEL_REGISTRY: readonly PanelConfig[] = [
  // ── DEFAULT OPEN + LOCKED (always visible) ──
  {
    id: PANEL_ID.PATIENT_SNAPSHOT,
    label: 'Patient',
    icon: Heart,
    color: '#14b8a6',
    hoverBg: 'hover:bg-teal-700',
    defaultSize: { width: 360, height: 400 },
    minSize: { width: 280, height: 300 },
    defaultPosition: { x: 0, y: 0 },
    defaultLocked: true,
    defaultOpen: true,
    locksWithChart: false,
    category: 'clinical',
  },
  {
    id: PANEL_ID.SOAP,
    label: 'SOAP',
    icon: PenTool,
    color: '#3b82f6',
    hoverBg: 'hover:bg-blue-700',
    defaultSize: { width: 600, height: 700 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 370, y: 0 },
    defaultLocked: true,
    defaultOpen: true,
    locksWithChart: true,
    category: 'clinical',
  },

  // ── CLINICAL PANELS (toolbar, open on click) ──
  {
    id: PANEL_ID.MEDICATION_HISTORY,
    label: 'Med Hx',
    icon: Pill,
    color: '#a855f7',
    hoverBg: 'hover:bg-purple-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 100, y: 50 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.ORDERS,
    label: 'Orders',
    icon: ClipboardList,
    color: '#3b82f6',
    hoverBg: 'hover:bg-blue-700',
    defaultSize: { width: 520, height: 650 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 120, y: 60 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.PRESCRIPTION_HISTORY,
    label: 'Rx Hx',
    icon: FileText,
    color: '#14b8a6',
    hoverBg: 'hover:bg-teal-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 140, y: 70 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.APPOINTMENTS,
    label: 'Appts',
    icon: CalendarDays,
    color: '#f97316',
    hoverBg: 'hover:bg-orange-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 350 },
    defaultPosition: { x: 160, y: 80 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.ALLERGIES,
    label: 'Allergy',
    icon: AlertTriangle,
    color: '#ef4444',
    hoverBg: 'hover:bg-red-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 180, y: 90 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.VITALS,
    label: 'Vitals',
    icon: Activity,
    color: '#06b6d4',
    hoverBg: 'hover:bg-cyan-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 200, y: 100 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.MEDICATIONS,
    label: 'Meds',
    icon: Pill,
    color: '#10b981',
    hoverBg: 'hover:bg-emerald-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 220, y: 110 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.DEMOGRAPHICS,
    label: 'Demo',
    icon: User,
    color: '#64748b',
    hoverBg: 'hover:bg-slate-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 240, y: 120 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.PROBLEMS,
    label: 'Problems',
    icon: AlertCircle,
    color: '#f97316',
    hoverBg: 'hover:bg-orange-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 260, y: 130 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.CLINICAL_NOTES,
    label: 'Notes',
    icon: FileText,
    color: '#3b82f6',
    hoverBg: 'hover:bg-blue-700',
    defaultSize: { width: 520, height: 650 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 280, y: 140 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.LAB_RESULTS,
    label: 'Labs',
    icon: FlaskConical,
    color: '#06b6d4',
    hoverBg: 'hover:bg-cyan-700',
    defaultSize: { width: 520, height: 600 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 300, y: 150 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.IMMUNIZATIONS,
    label: 'Immun',
    icon: Syringe,
    color: '#10b981',
    hoverBg: 'hover:bg-emerald-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 320, y: 160 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.DOCUMENTS,
    label: 'Docs',
    icon: FolderOpen,
    color: '#f59e0b',
    hoverBg: 'hover:bg-amber-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 340, y: 170 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.FAMILY_HISTORY,
    label: 'Fam Hx',
    icon: Users,
    color: '#f43f5e',
    hoverBg: 'hover:bg-rose-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 360, y: 180 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.SOCIAL_HISTORY,
    label: 'Social',
    icon: Wine,
    color: '#f59e0b',
    hoverBg: 'hover:bg-amber-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 380, y: 190 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.SURGICAL_HISTORY,
    label: 'Surg Hx',
    icon: Scissors,
    color: '#ef4444',
    hoverBg: 'hover:bg-red-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 400, y: 200 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.PHARMACY,
    label: 'Pharmacy',
    icon: Building2,
    color: '#14b8a6',
    hoverBg: 'hover:bg-teal-700',
    defaultSize: { width: 440, height: 500 },
    minSize: { width: 320, height: 350 },
    defaultPosition: { x: 420, y: 210 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.CARE_PLANS,
    label: 'Care Plan',
    icon: ClipboardCheck,
    color: '#a855f7',
    hoverBg: 'hover:bg-purple-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 440, y: 220 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.BILLING,
    label: 'Billing',
    icon: DollarSign,
    color: '#10b981',
    hoverBg: 'hover:bg-emerald-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 460, y: 230 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.COMM_HUB,
    label: 'Comms',
    icon: MessageSquare,
    color: '#3b82f6',
    hoverBg: 'hover:bg-blue-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 480, y: 240 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'communication',
  },
  {
    id: PANEL_ID.LAB_ORDERS,
    label: 'Lab Orders',
    icon: FlaskConical,
    color: '#0ea5e9',
    hoverBg: 'hover:bg-sky-700',
    defaultSize: { width: 520, height: 600 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 500, y: 250 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.REFERRALS,
    label: 'Referrals',
    icon: ArrowRight,
    color: '#f97316',
    hoverBg: 'hover:bg-orange-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 520, y: 260 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: true,
    category: 'clinical',
  },
  {
    id: PANEL_ID.PRIOR_AUTH,
    label: 'Prior Auth',
    icon: ClipboardCheck,
    color: '#8b5cf6',
    hoverBg: 'hover:bg-violet-700',
    defaultSize: { width: 480, height: 550 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 540, y: 270 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'administrative',
  },
  {
    id: PANEL_ID.CHART_MANAGEMENT,
    label: 'Chart',
    icon: Shield,
    color: '#a855f7',
    hoverBg: 'hover:bg-purple-700',
    defaultSize: { width: 520, height: 650 },
    minSize: { width: 400, height: 450 },
    defaultPosition: { x: 560, y: 280 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'system',
  },
  {
    id: PANEL_ID.ERX,
    label: 'eRx',
    icon: Stethoscope,
    color: '#22c55e',
    hoverBg: 'hover:bg-green-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 580, y: 290 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'clinical',
  },
  {
    id: PANEL_ID.VIDEO,
    label: 'Video',
    icon: Video,
    color: '#06b6d4',
    hoverBg: 'hover:bg-cyan-700',
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 480, height: 360 },
    defaultPosition: { x: 600, y: 300 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'communication',
  },

  // ── SYSTEM PANELS ──
  {
    id: PANEL_ID.COSIGN_QUEUE,
    label: 'Cosign Queue',
    icon: CheckSquare,
    color: '#f59e0b',
    hoverBg: 'hover:bg-amber-700',
    defaultSize: { width: 480, height: 600 },
    minSize: { width: 360, height: 400 },
    defaultPosition: { x: 620, y: 310 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'system',
  },
  {
    id: PANEL_ID.AUDIT_TRAIL,
    label: 'Audit',
    icon: BookOpen,
    color: '#64748b',
    hoverBg: 'hover:bg-slate-700',
    defaultSize: { width: 520, height: 600 },
    minSize: { width: 400, height: 400 },
    defaultPosition: { x: 640, y: 320 },
    defaultLocked: false,
    defaultOpen: false,
    locksWithChart: false,
    category: 'system',
  },
] as const

// ─── LOOKUP HELPERS ──────────────────────────────────────────
export function getPanelConfig(id: PanelId): PanelConfig | undefined {
  return PANEL_REGISTRY.find(p => p.id === id)
}

export function getPanelsByCategory(category: PanelConfig['category']): readonly PanelConfig[] {
  return PANEL_REGISTRY.filter(p => p.category === category)
}

export function getDefaultOpenPanels(): readonly PanelConfig[] {
  return PANEL_REGISTRY.filter(p => p.defaultOpen)
}

export function getToolbarPanels(): readonly PanelConfig[] {
  // All panels except the default-open ones (those are always visible)
  return PANEL_REGISTRY.filter(p => !p.defaultOpen)
}
